# Generated by Django 5.1.3 on 2024-12-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super admin', 'Super admin'), ('Admin', 'Admin'), ('User', 'User')], default='User', max_length=50),
        ),
    ]
