# Generated by Django 5.1.3 on 2024-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super admin', 'super admin'), ('Admin', 'admin'), ('User', 'user')], default='User', max_length=50),
        ),
    ]
