# Generated by Django 5.1.3 on 2024-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super admin', 'super admin'), ('admin', 'admin'), ('user', 'user')], default='User', max_length=50),
        ),
    ]
