# Generated by Django 5.1.4 on 2024-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_assigned_to_name_company_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_project',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='not started', max_length=50),
        ),
    ]
